### PR TITLE
Authentication

### PR DESCRIPTION
**Pull request by fkoolhoven**
## Description
An upgrade for the authentication process, hopefully making everything more reliable and adding 2FA to the user account.

### 2FA
- User can enable and disable 2FA through a button in the User Account
- To set up 2FA the user has to scan a qrcode and submit a one time password
- If set-up is successfully completed, 2FA enabled is set to TRUE in database
- When user logs in, this boolean is checked
- If user has 2FA enabled, they are redirect to the Verify2FA page
- Added secret key field to user in database, which is used to verify one time passwords

### Login
- If the user is already authenticated, they are automatically redirected to /main, meaning they don't have to log in again

### Logout
- User can be logged out by redirecting to /logout
- User is logged out when LogOutButton is used, or when a ProtectedRoute detects the token has expired
- User status is changed to Offline upon logging out

### Other
- Some refactoring here and there, would appreciate feedback

### CODE REVIEW

**Review by maresverbrugge — CHANGES_REQUESTED** [review]
I tested the functionality and am very happy to report it all works GREAT. I tried logging in and out with both the 2FA functionality enabled and disabled and both worked as expected. Also tried a wrong authentication code and the "cancel" button. All of these actions update the database accordingly. 

- we agreed we both feel sad about removing the "toggle" button so we might implement it somewhere else.
- we can add an info field saying the functionality is disabled and a button to enable it and vice versa instead of the toggle (or maybe maybe even bring back the toggle, if it makes sense and is not that hard to implement?)
- we can add a little extra information about use of the Google Authenticator app.

Code looks good overall! Very clean and in one style. I like the elaborate error handling. Also seems like you payed great attention to async/await and when it's really needed to wait and when not. 
We spoke about a few little things:
- I couldn't successfully compile again without first deleting the migrations folder first. This is not something you can improve, but good for the others to know too.
- for the files Login.tsx and ProtectedRoute.tsx the import of component isAuthenticatedHook from "hooks" folder in the frontend didn't work because of mismatch in capitalization (Hooks or hooks)

Some more things:
- Noticed the "apiCalls.tsx" in pages, looks very overzichtelijk. Would like for us 4 to make an agreement to use it all. 
- We should really decide all 4 of us if we're using things like "React.FC" or not.
- I don't follow the "speakeasy" stuff a 100%, but i'm excited for you explanation! 
- also saw you use try, catch, and "finally" and i am very curious about that and when to use it.

GOOD WORK FELIC! 🏆

**Comment by fkoolhoven** [comment]
Hey Mrazzle,

I made these changes:
- hooks dir -> Hooks dir
- Above the button in the User Account there's a line that tells you if 2FA is currently enabled or disabled
- Set up 2FA now also has instruction to download the Google Authenticator app
- Moved api calls file up a level (out of Authentication) so it invites other devs to use it as well.

Your questions:
- Speakeasy I can explain more in depth in person but we use it to generate a secret key that is shared between our database and the user's google authenticator app. The qrcode we make is 'built' from this secret. We can then use that secret key to verify the user's time based passwords.
- Finally is awesome. Unlike catch (which is only triggered upon error), finally is ALWAYS triggered. So if there is code that you need to be executed if there IS an error but also if there is NOT an error, you can put it in a finally block. Think of disposing of resources or setting an 'isLoading' variable to false (that's how I'm mostly using it).
- "React.FC"... agreed, I don't really understand it myself yet, but saw it in online examples hehe

**Review by maresverbrugge — APPROVED** [review]

**Comment by maresverbrugge** [comment]
Great changes!
I really like how you made the apiCalls file and moved it to encourage us to use it too. Also enjoyed the explanation of Finally and I want to use it everywhere myself now.
Glad 2FA works so successfully, good job Felicia!!

**Review by fhuisman — COMMENTED** [review]
A little late but i reviewed this PR and I am happy I did!
Looks great, I'm gonna study some of your coding patterns and try to use them myself. Like the hooks you made and the 'loading...' or 'submitting...' messages while making an api call.
I'm also interested to hear more about the one time password and how the speakeasy thing and the qr code work..

**Pull request merged**
